default_stages: [
    commit,
    merge-commit,
    push,
    prepare-commit-msg,
    commit-msg,
    post-checkout,
    post-commit,
    post-merge,
    post-rewrite
]
repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: python -m flake8
        language: system
        types: [python]
