matrix:
    include:
        - os: linux
          language: python
          python: 2.7
        - os: linux
          language: python
          python: 3.6
        - os: linux
          dist: xenial
          language: python
          python: 3.7
        - os: osx
          language: generic

before_install:
    # OSX setup
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then
          python3 -m venv environment;
          source environment/bin/activate;
      fi

install:
    - pip install Cython numpy
    - pip install -r requirements.txt
    - pip install pytest-cov codecov
    - pip install flake8 pydocstyle sphinx sphinx_rtd_theme

before_script:
    - "export MPLBACKEND=Agg"

    # Test for pep-compliance
    - flake8 anesthetic tests

    # Test for documentation style
    - pydocstyle anesthetic

# Run tests
script:
      python -m pytest tests --cov=anesthetic;

# Run coverage summary
after_success:
    - codecov
