# linux matrix
language: python
os: linux
python:
    - "3.6"
    - "2.7"

# OSX matrix
matrix:
    include:
        - os: osx
          language: generic
          env: PYTHON_VERSION=python2
        - os: osx
          language: generic
          env: PYTHON_VERSION=python3

install:
    - pip install Cython numpy
    - pip install -r requirements.txt
    - pip install pytest-cov codecov
    - pip install flake8 pydocstyle sphinx sphinx_rtd_theme

addons:
    homebrew:
        packages: 
            - python2
            - python3

before_install:
    # OSX setup
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then 
          if [[ "$PYTHON_VERSION" == "python2" ]];
          then
              pip install virtualenv;
              virtualenv venv -p $PYTHON_VERSION;
          else;
              $PYTHON_VERSION -m venv environment;
          fi;
          source environment/bin/activate;
      fi

before_script:
    - "export MPLBACKEND=Agg"

    # Test for pep-compliance
    - flake8 anesthetic tests

    # Test for documentation style
    - pydocstyle anesthetic

# Run tests
script:
      python -m pytest tests --cov=anesthetic;

# Run coverage summary
after_success:
    - codecov
