version: 2
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: setup Python venv
          command: |
            python3 -m venv venv

      - run: 
          name: install
          command: |
            . venv/bin/activate
            pip install Cython numpy
            pip install -r requirements.txt
            pip install pytest pytest-cov codecov
            pip install flake8 pydocstyle sphinx sphinx_rtd_theme

      - run: 
          name: flake8
          command: |
            . venv/bin/activate
            flake8 anesthetic tests 

      - run: 
          name: pydocstyle
          command: |
            . venv/bin/activate
            pydocstyle anesthetic 

      - run: 
          name: tests
          command: |
            . venv/bin/activate
            python -m pytest tests


workflows:
  version: 2
  circle-ci:
    jobs:
      - run_tests
